import sys
sys.stdout.reconfigure(encoding='utf-8')
with open('index.html','r',encoding='utf-8') as f:
    lines = f.readlines()

func = (
"function renderHistoricoAtendimento(main) {\n"
"  var busca = (state._histBusca||'').toLowerCase().trim();\n"
"  var filtroPeriodo = state._histPeriodo||'';\n"
"  var tipoFiltro = state._histTipo||'';\n"
"\n"
"  var registros = [];\n"
"\n"
"  // Ocorrencias encerradas\n"
"  (state.db.ocorrencias||[]).forEach(function(o){\n"
"    if(!(o.status==='encerrada'||o.status==='encerrado'||o.encerrada)) return;\n"
"    registros.push({\n"
"      tipo:'ocorrencia', icone:'\\u{1F4CB}',\n"
"      data:o.data||'',\n"
"      titulo:'OC #'+(o.numero||o.id||'')+(o.tipo?' \\u2014 '+o.tipo:''),\n"
"      subtitulo:o.nome_vitima||o.envolvidos||'',\n"
"      descricao:o.narrativa||o.descricao||'',\n"
"      bairro:o.bairro||'', status:o.status||'encerrada', cor:'var(--tinta-2)'\n"
"    });\n"
"  });\n"
"\n"
"  // Atendimentos\n"
"  (state.db.atendimentos||[]).forEach(function(a){\n"
"    registros.push({\n"
"      tipo:'atendimento', icone:'\\u{1F91D}',\n"
"      data:a.data||'',\n"
"      titulo:'Atendimento'+(a.tipo?' \\u2014 '+a.tipo:''),\n"
"      subtitulo:a.nome||a.envolvido||'',\n"
"      descricao:a.descricao||a.observacoes||'',\n"
"      bairro:a.bairro||a.local||'', status:a.status||'realizado', cor:'var(--azul)'\n"
"    });\n"
"  });\n"
"\n"
"  // Encaminhamentos concluidos\n"
"  (state.encaminhamentos||[]).filter(function(e){return e.status==='concluido';}).forEach(function(e){\n"
"    registros.push({\n"
"      tipo:'encaminhamento', icone:'\\u{1F4E4}',\n"
"      data:e.data||'',\n"
"      titulo:'Encaminhamento \\u2014 '+(e.destino||e.orgao||''),\n"
"      subtitulo:e.nome||e.vitima||'',\n"
"      descricao:e.descricao||e.relato_devolutiva||'',\n"
"      bairro:'', status:'conclu\\u00EDdo', cor:'var(--verde)'\n"
"    });\n"
"  });\n"
"\n"
"  registros.sort(function(a,b){return (b.data||'').localeCompare(a.data||'');});\n"
"\n"
"  var hoje_iso = hoje();\n"
"  if(filtroPeriodo){\n"
"    registros = registros.filter(function(r){\n"
"      var d=(r.data||'').substring(0,10);\n"
"      if(filtroPeriodo==='hoje') return d===hoje_iso;\n"
"      if(filtroPeriodo==='semana'){\n"
"        var ms=new Date(hoje_iso).getTime(); var rd=new Date(d).getTime();\n"
"        return (ms-rd)>=0&&(ms-rd)<7*86400000;\n"
"      }\n"
"      if(filtroPeriodo==='mes') return d.substring(0,7)===hoje_iso.substring(0,7);\n"
"      return true;\n"
"    });\n"
"  }\n"
"\n"
"  var filtrados = registros.filter(function(r){\n"
"    if(!busca) return true;\n"
"    return (r.titulo+r.subtitulo+r.descricao+r.bairro+r.data).toLowerCase().indexOf(busca)>=0;\n"
"  });\n"
"\n"
"  if(tipoFiltro) filtrados = filtrados.filter(function(r){return r.tipo===tipoFiltro;});\n"
"\n"
"  var h = \"<div style='max-width:860px;margin:0 auto;padding:0 4px'>\";\n"
"\n"
"  h += \"<div style='display:flex;align-items:center;gap:12px;margin-bottom:16px;flex-wrap:wrap'>\";\n"
"  h += \"<h2 style='font-family:Georgia,serif;font-size:20px;font-weight:700;color:var(--tinta);margin:0'>\\u{1F5C2}\\uFE0F Hist\\u00F3rico de Atendimentos</h2>\";\n"
"  h += \"<span style='background:var(--papel-3);color:var(--tinta-2);border-radius:12px;padding:2px 10px;font-size:12px'>\"+filtrados.length+\" registro\"+(filtrados.length!==1?'s':'')+\" encontrado\"+(filtrados.length!==1?'s':'')+\"</span>\";\n"
"  h += \"</div>\";\n"
"\n"
"  h += \"<div style='display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap'>\";\n"
"  h += \"<div style='flex:1;min-width:200px;position:relative'>\";\n"
"  h += \"<span style='position:absolute;left:10px;top:50%;transform:translateY(-50%);font-size:14px;pointer-events:none'>\\u{1F50D}</span>\";\n"
"  h += \"<input id='hist-busca' type='text' value='\"+esc(state._histBusca||'')+\"' \"\n"
"     + \"placeholder='Buscar por nome, tipo, bairro, narrativa\\u2026' \"\n"
"     + \"oninput='state._histBusca=this.value;renderHistoricoAtendimento(document.getElementById(\\\"fila-dia-content\\\"))' \"\n"
"     + \"style='width:100%;box-sizing:border-box;padding:9px 12px 9px 34px;border:1px solid var(--papel-3);border-radius:8px;background:var(--papel);color:var(--tinta);font-size:13px'>\";\n"
"  h += \"</div>\";\n"
"  var periodos=[{v:'',l:'Todos'},{v:'hoje',l:'Hoje'},{v:'semana',l:'7 dias'},{v:'mes',l:'Este m\\u00EAs'}];\n"
"  h += \"<div style='display:flex;gap:4px'>\";\n"
"  periodos.forEach(function(p){\n"
"    var av=filtroPeriodo===p.v;\n"
"    h += \"<button onclick='state._histPeriodo=\\\"\"+p.v+\"\\\";renderHistoricoAtendimento(document.getElementById(\\\"fila-dia-content\\\"))' \"\n"
"       + \"style='padding:8px 11px;border:1px solid \"+(av?'var(--azul)':'var(--papel-3)')+\";border-radius:8px;background:\"+(av?'var(--azul)':'var(--papel)')+\";color:\"+(av?'#fff':'var(--tinta-2)')+\";font-size:11px;font-weight:\"+(av?'700':'400')+\";cursor:pointer;white-space:nowrap'>\"+p.l+\"</button>\";\n"
"  });\n"
"  h += \"</div></div>\";\n"
"\n"
"  h += \"<div style='display:flex;gap:6px;margin-bottom:16px;flex-wrap:wrap'>\";\n"
"  [{v:'',l:'Todos',ic:''},{v:'ocorrencia',l:'Ocorr\\u00EAncias',ic:'\\u{1F4CB}'},{v:'atendimento',l:'Atendimentos',ic:'\\u{1F91D}'},{v:'encaminhamento',l:'Encaminhamentos',ic:'\\u{1F4E4}'}].forEach(function(t){\n"
"    var av=tipoFiltro===t.v;\n"
"    h += \"<button onclick='state._histTipo=\\\"\"+t.v+\"\\\";renderHistoricoAtendimento(document.getElementById(\\\"fila-dia-content\\\"))' \"\n"
"       + \"style='padding:5px 12px;border-radius:20px;border:1px solid \"+(av?'var(--azul)':'var(--papel-3)')+\";background:\"+(av?'var(--azul)':'transparent')+\";color:\"+(av?'#fff':'var(--tinta-2)')+\";font-size:11px;font-weight:\"+(av?'700':'400')+\";cursor:pointer'>\"+(t.ic?t.ic+' ':'')+t.l+\"</button>\";\n"
"  });\n"
"  h += \"</div>\";\n"
"\n"
"  if(!filtrados.length){\n"
"    h += \"<div class='card' style='text-align:center;padding:56px'>\";\n"
"    h += \"<p style='font-size:32px;margin-bottom:10px'>\\u{1F50E}</p>\";\n"
"    h += \"<p style='font-size:15px;font-weight:700;color:var(--tinta);font-family:Georgia,serif'>Nenhum registro encontrado</p>\";\n"
"    h += \"<p style='font-size:13px;color:var(--tinta-2);margin-top:6px'>Tente outros termos ou ajuste o filtro.</p>\";\n"
"    h += \"</div>\";\n"
"  } else {\n"
"    filtrados.forEach(function(r){\n"
"      var dFmt=(r.data||'').substring(0,10);\n"
"      h += \"<div class='card' style='margin-bottom:10px;padding:14px 16px;border-left:3px solid \"+r.cor+\"'>\";\n"
"      h += \"<div style='display:flex;align-items:flex-start;gap:10px'>\";\n"
"      h += \"<span style='font-size:18px;flex-shrink:0;margin-top:1px'>\"+r.icone+\"</span>\";\n"
"      h += \"<div style='flex:1;min-width:0'>\";\n"
"      h += \"<div style='display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:3px'>\";\n"
"      h += \"<span style='font-size:13px;font-weight:700;color:var(--tinta)'>\"+esc(r.titulo)+\"</span>\";\n"
"      if(r.subtitulo) h += \"<span style='font-size:12px;color:var(--tinta-2)'>\"+esc(r.subtitulo)+\"</span>\";\n"
"      h += \"</div>\";\n"
"      if(r.descricao){\n"
"        var desc=r.descricao.length>160?r.descricao.substring(0,160)+'\\u2026':r.descricao;\n"
"        h += \"<p style='font-size:12px;color:var(--tinta-2);margin:4px 0 0;line-height:1.45'>\"+esc(desc)+\"</p>\";\n"
"      }\n"
"      h += \"<div style='display:flex;gap:10px;margin-top:6px;flex-wrap:wrap'>\";\n"
"      if(dFmt) h += \"<span style='font-size:11px;color:var(--tinta-3)'>\\u{1F4C5} \"+esc(dFmt)+\"</span>\";\n"
"      if(r.bairro) h += \"<span style='font-size:11px;color:var(--tinta-3)'>\\u{1F4CD} \"+esc(r.bairro)+\"</span>\";\n"
"      h += \"<span style='font-size:10px;background:var(--papel-3);color:var(--tinta-2);border-radius:10px;padding:1px 7px'>\"+esc(r.status)+\"</span>\";\n"
"      h += \"</div></div></div></div>\";\n"
"    });\n"
"  }\n"
"\n"
"  h += \"</div>\";\n"
"  main.innerHTML = h;\n"
"  setTimeout(function(){var el=document.getElementById('hist-busca');if(el&&!busca)el.focus();},80);\n"
"}\n"
"\n"
)

for i,l in enumerate(lines):
    if 'function renderFilaDia(' in l:
        insert_at = i
        break

new_lines = lines[:insert_at] + [func] + lines[insert_at:]
with open('index.html','w',encoding='utf-8') as f:
    f.writelines(new_lines)
print('OK - inserido em linha', insert_at+1)
